### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by zzkt** [citizenos/ep_image_upload#14]
Looks like the `image_upload` and  `copy_paste_images` plugins stopped working somewhere between etherpad versions 1.8.3 and 1.8.4.

Pads with images (working on 1.8.3 and HEAD as of May 13th) will get stuck at "Loading..." or give an error after updating to 1.8.4...

```
console - (node:25175) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
     at Function.keys (<anonymous>)
     at Object.exports.clientVars [as hook_fn] (/var/www/etherpad/node_modules/ep_image_upload/static/js/serverHooks.js:36:23)
     at normalizedhook (/var/www/etherpad/src/static/js/pluginfw/hooks.js:15:27)
     at hookCallWrapper (/var/www/etherpad/src/static/js/pluginfw/hooks.js:21:14)
     at /var/www/etherpad/src/static/js/pluginfw/hooks.js:88:7
     at /var/www/etherpad/src/node_modules/async/lib/async.js:249:17
     at /var/www/etherpad/src/node_modules/async/lib/async.js:125:13
     at Array.forEach (<anonymous>)
     at _each (/var/www/etherpad/src/node_modules/async/lib/async.js:46:24)
     at async.each (/var/www/etherpad/src/node_modules/async/lib/async.js:124:9)
     at _asyncMap (/var/www/etherpad/src/node_modules/async/lib/async.js:248:13)
     at Object.map (/var/www/etherpad/src/node_modules/async/lib/async.js:219:23)
     at aCallAll (/var/www/etherpad/src/static/js/pluginfw/hooks.js:85:9)
     at /var/www/etherpad/src/static/js/pluginfw/hooks.js:100:7
     at new Promise (<anonymous>)
     at Object.exports.aCallAll (/var/www/etherpad/src/static/js/pluginfw/hooks.js:99:12)
     at handleClientReady (/var/www/etherpad/src/node/handler/PadMessageHandler.js:1142:32)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)

console - (node:25175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

```

...also submitted [here](https://github.com/JohnMcLear/ep_copy_paste_images/issues/20)

**Comment by zzkt** [comment]
fixed upstream. https://github.com/ether/etherpad-lite/pull/4054
