### ISSUE TITLE
does not work with  etherpad 1.7.5

### ISSUE THREAD

**Issue by revast** [citizenos/ep_image_upload#7]
button works,  and I  can select an image, but upload fails, image does not appear (base64 method):

 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.clientVars [as hook_fn] (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_image_upload\static\js\serverHooks.js:36:23)
    at normalizedhook (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:15:27)
    at hookCallWrapper (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:21:14)
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:88:7
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:249:17
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:125:13
    at Array.forEach (<anonymous>)
    at _each (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:46:24)
    at async.each (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:124:9)
    at _asyncMap (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:248:13)
    at Object.map (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:219:23)
    at Object.exports.aCallAll (C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:85:9)
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node\handler\PadMessageHandler.js:1346:15
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:610:21
    at C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_etherpad-lite\node_modules\async\lib\async.js:249:17

**Comment by agilob** [comment]
You need to configure it as in readme.

**Comment by tiblu** [comment]
Thanks for the report! 
Was it a configuration issue? Feel free to reopen issue if there is still a problem.
Currently we develop and test and support ep_image_upload for EP >=1.8, we don't guarantee it working on older versions.
